name: Watcher-sockets

on:
  push:
    branches:
      - testing

jobs:
  build-and-push:
    environment: testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image with Maven
        run: |
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ vars.DOCKER_USERNAME }}/watcher-api  -Dspring-boot.build-image.publish=false
          docker push ${{ vars.DOCKER_USERNAME }}/watcher-api

  deployment:
    environment: testing
    runs-on: ubuntu-latest
    needs:   build-and-push # This line ensures deployment runs after "docker" job finishess
    steps:
      - name: Stopping running image  # Corrected capitalization
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.HOST_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            docker container stop watcher-api-testing  # Consistent use of double quotes
            docker container rm watcher-api-testing  # Consistent use of double quotes
            docker pull ${{ secrets.DOCKER_USERNAME }}/watcher-api:${{github.sha}}  # Consistent use of double quotes
            docker run  \
              -d \
              -e SITES_BASE_URI=/logs \
              -e JAVA_OPTS="-Xss512k" \
              -e BPL_JVM_HEAD_ROOM=5 \
              -e BPL_JVM_LOADED_CLASS_COUNT=30000 \
              -e BPL_JVM_THREAD_COUNT=50 \
              -e BPL_JVM_DIRECT_MEMORY=8M \
              -e BPL_JVM_METASPACE=64M \
              -e BPL_JVM_RESERVED_CODE_CACHE=32M \
              -e BPL_JVM_STACK=512K \
              -v /home/actions/logs/:/logs \
              --name watcher-api-testing \
              -p 9090:8080 \
              --restart unless-stopped \
              ${{ vars.DOCKER_USERNAME }}/watcher-api:latest
